# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_adding_image_fields_for_drew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='controlpoint',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='controlpoint',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='controlpoint',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='coordinatesystem',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='coordinatesystem',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='coordinatesystem',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='coordinatetransform',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='coordinatetransform',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='coordinatetransform',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='image',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='image',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='image',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='imagecollection',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='imagecollection',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='imagecollection',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='pointcloud',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='pointcloud',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='pointcloud',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='tiepoint',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='tiepoint',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='tiepoint',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='voxelworld',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='voxelworld',
            name='newerVersion',
        ),
        migrations.RemoveField(
            model_name='voxelworld',
            name='objectId',
        ),
        migrations.DeleteModel(
            name='WorkflowInstance',
        ),
    ]
