# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0012_auto_20160819_1427'),
        ('meta', '0012_merge'),
    ]

    operations = [
    ]
