# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 00:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_merge_20160917_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satteleventtrigger',
            name='event_areas',
            field=models.ManyToManyField(default=[], related_name='event_event_trigger', to='meta.SattelGeometryObject'),
        ),
        migrations.AlterField(
            model_name='satteleventtrigger',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(default=b'POINT(0 0 0)', dim=3, srid=4326),
        ),
        migrations.AlterField(
            model_name='satteleventtrigger',
            name='reference_areas',
            field=models.ManyToManyField(default=[], related_name='reference_event_trigger', to='meta.SattelGeometryObject'),
        ),
    ]
