# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_auto_20160917_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satteleventtrigger',
            name='event_areas',
            field=models.ManyToManyField(blank=True, default=[], related_name='event_event_trigger', to='meta.SattelGeometryObject'),
        ),
        migrations.AlterField(
            model_name='satteleventtrigger',
            name='reference_areas',
            field=models.ManyToManyField(blank=True, default=[], related_name='reference_event_trigger', to='meta.SattelGeometryObject'),
        ),
    ]
