# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0015_allow_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satteleventtrigger',
            name='origin',
        ),
    ]
